### ISSUE TITLE
Error when starting app

### ISSUE THREAD

**Issue by gkillg** [vanhbakaa/PocketFi#1]
Hello!
I was about to try out your code, and i've got an error,but i like your idea about bot!
OS: Windows 10 LTSC
Here's error:

> Traceback (most recent call last):
  File "D:\Programs\Python\projects\PocketFi-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\Programs\Python\projects\PocketFi-main\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\Programs\Python\projects\PocketFi-main\bot\utils\launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "D:\Programs\Python\Lib\site-packages\better_proxy\__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "D:\Programs\Python\Lib\site-packages\better_proxy\proxy.py", line 28, in <module>
    class Proxy(BaseModel):
  File "D:\Programs\Python\Lib\site-packages\pydantic\main.py", line 299, in __new__
    fields[ann_name] = ModelField.infer(
                       ^^^^^^^^^^^^^^^^^
  File "D:\Programs\Python\Lib\site-packages\pydantic\fields.py", line 411, in infer
    return cls(
           ^^^^
  File "D:\Programs\Python\Lib\site-packages\pydantic\fields.py", line 342, in __init__
    self.prepare()
  File "D:\Programs\Python\Lib\site-packages\pydantic\fields.py", line 451, in prepare
    self._type_analysis()
  File "D:\Programs\Python\Lib\site-packages\pydantic\fields.py", line 626, in _type_analysis
    raise TypeError(f'Fields of type "{origin}" are not supported.')
TypeError: Fields of type "<class 'types.UnionType'>" are not supported.

Thank you for the bot!

**Comment by vanhbakaa** [comment]
what is your python version

**Comment by EmmyManifest** [comment]
Select an action:

    1. Run clicker
    2. Create session

> 1
2024-10-02 02:12:39 | INFO     | 219 - lfg | Start after 26s...
2024-10-02 02:12:39 | ERROR    | 212 - lfg | Unknown error: list index out of range
2024-10-02 02:13:42 | ERROR    | 212 - lfg | Unknown error: list index out of range
2024-10-02 02:14:59 | ERROR    | 212 - lfg | Unknown error: list index out of range
